from typing import List, Dict


class Model:
    def predict(self, sentences: List[Dict]) -> List[List[str]]:
        """
        A simple wrapper for your model

        Args: sentences: list of sentences with words to disambiguate. Each sentence is represented with a dict.
        Ex. of input list containing two sentences:
            [
                {
                    "id": "d000.s000",
                    "instance_ids": {
                        "9": "d000.s000.t000",
                        "11": "d000.s000.t001",
                        "21": "d000.s000.t002"
                    },
                    "lemmas": [
                        "you",
                        "oct.",
                        "6",
                        "editorial",
                        "``",
                        "the",
                        "ill",
                        "homeless",
                        "``",
                        "refer",
                        "to",
                        "research",
                        "by",
                        "we",
                        "and",
                        "six",
                        "of",
                        "we",
                        "colleague",
                        "that",
                        "be",
                        "report",
                        "in",
                        "the",
                        "sept.",
                        "8",
                        "issue",
                        "of",
                        "the",
                        "journal",
                        "of",
                        "the",
                        "american",
                        "medical",
                        "association",
                        "."
                    ],
                    "pos_tags": [
                        "PRON",
                        "NOUN",
                        "NUM",
                        "NOUN",
                        ".",
                        "DET",
                        "NOUN",
                        "NOUN",
                        ".",
                        "VERB",
                        "PRT",
                        "NOUN",
                        "ADP",
                        "PRON",
                        "CONJ",
                        "NUM",
                        "ADP",
                        "PRON",
                        "NOUN",
                        "DET",
                        "VERB",
                        "VERB",
                        "ADP",
                        "DET",
                        "NOUN",
                        "NUM",
                        "NOUN",
                        "ADP",
                        "DET",
                        "NOUN",
                        "ADP",
                        "DET",
                        "NOUN",
                        "NOUN",
                        "NOUN",
                        "."
                    ],
                    "words": [
                        "Your",
                        "Oct.",
                        "6",
                        "editorial",
                        "``",
                        "The",
                        "Ill",
                        "Homeless",
                        "``",
                        "referred",
                        "to",
                        "research",
                        "by",
                        "us",
                        "and",
                        "six",
                        "of",
                        "our",
                        "colleagues",
                        "that",
                        "was",
                        "reported",
                        "in",
                        "the",
                        "Sept.",
                        "8",
                        "issue",
                        "of",
                        "the",
                        "Journal",
                        "of",
                        "the",
                        "American",
                        "Medical",
                        "Association",
                        "."
                    ],
                    "candidates": {
                        "9": [
                            "concerned.v.h.01",
                            "denote.v.h.01",
                            "consult.v.h.01",
                            "refer.v.h.01",
                            "naming.v.h.01"
                        ],
                        "11": [
                            "enquiry.n.h.01",
                            "research.n.h.01"
                        ],
                        "21": [
                            "described.v.h.01",
                            "covered.v.h.01",
                            "reported.v.h.01"
                        ]
                    }
                },
                {
                    "id": "d000.s001",
                    "instance_ids": {
                        "1": "d000.s001.t000",
                        "2": "d000.s001.t001",
                        "5": "d000.s001.t002",
                        "10": "d000.s001.t003",
                        "17": "d000.s001.t004"
                    },
                    "lemmas": [
                        "you",
                        "comment",
                        "imply",
                        "we",
                        "have",
                        "discover",
                        "that",
                        "the",
                        "``",
                        "principal",
                        "cause",
                        "``",
                        "of",
                        "homelessness",
                        "be",
                        "to",
                        "be",
                        "find",
                        "in",
                        "the",
                        "large",
                        "number",
                        "of",
                        "mentally",
                        "ill",
                        "and",
                        "substance-abusing",
                        "people",
                        "in",
                        "the",
                        "homeless",
                        "population",
                        "."
                    ],
                    "pos_tags": [
                        "PRON",
                        "NOUN",
                        "VERB",
                        "PRON",
                        "VERB",
                        "VERB",
                        "ADP",
                        "DET",
                        ".",
                        "ADJ",
                        "NOUN",
                        ".",
                        "ADP",
                        "NOUN",
                        "VERB",
                        "PRT",
                        "VERB",
                        "VERB",
                        "ADP",
                        "DET",
                        "ADJ",
                        "NOUN",
                        "ADP",
                        "ADV",
                        "ADJ",
                        "CONJ",
                        "ADJ",
                        "NOUN",
                        "ADP",
                        "DET",
                        "ADJ",
                        "NOUN",
                        "."
                    ],
                    "words": [
                        "Your",
                        "comments",
                        "implied",
                        "we",
                        "had",
                        "discovered",
                        "that",
                        "the",
                        "``",
                        "principal",
                        "cause",
                        "``",
                        "of",
                        "homelessness",
                        "is",
                        "to",
                        "be",
                        "found",
                        "in",
                        "the",
                        "large",
                        "numbers",
                        "of",
                        "mentally",
                        "ill",
                        "and",
                        "substance-abusing",
                        "people",
                        "in",
                        "the",
                        "homeless",
                        "population",
                        "."
                    ],
                    "candidates": {
                        "1": [
                            "comment.n.h.01"
                        ],
                        "2": [
                            "involved.v.h.01",
                            "connote.v.h.01",
                            "imply.v.h.01",
                            "incriminating.v.h.01",
                            "mean.v.h.01"
                        ],
                        "5": [
                            "found.v.h.09",
                            "found.v.h.08",
                            "discovered.v.h.01",
                            "described.v.h.01",
                            "broke.v.h.01",
                            "found.v.h.03",
                            "attained.v.h.01"
                        ],
                        "10": [
                            "case.n.h.01",
                            "causal_agency.n.h.01",
                            "cause.n.h.01",
                            "campaign.n.h.01"
                        ],
                        "17": [
                            "found.v.h.13",
                            "found.v.h.06",
                            "found.v.h.02",
                            "found.v.h.08",
                            "found.v.h.09",
                            "found.v.h.11",
                            "found.v.h.05",
                            "found.v.h.15",
                            "found.v.h.04",
                            "found.v.h.07",
                            "found.v.h.03",
                            "found.v.h.01",
                            "found.v.h.10",
                            "found.v.h.12",
                            "found.v.h.14"
                        ]
                    }
                }
            ]

        Returns:
            list of list of predictions associated to each word to disambiguate in the input sentences.
            Ex: [
                    ["naming.v.h.01", "research.n.h.01", "reported.v.h.01"],
                    ["comment.n.h.01", "connote.v.h.01", "discovered.v.h.01", "cause.n.h.01", "found.v.h.03"]
                ]

        """
        raise NotImplementedError
